id: stream
namespace: dev

inputs:
  - name: api_url
    type: STRING
    defaults: tcp://mosquitto_kestra

triggers:
  - id: subscribe
    type: "io.kestra.plugin.mqtt.Trigger"
    server: "tcp://mosquitto_kestra"
    clientId: KestraTrigger
    topic: 
      - /sample.it/jz/device/#
    serdeType: JSON
    maxRecords: 1
    
  - id: mongodb-insert
    type: "io.kestra.plugin.mongodb.InsertOne"
    connection:
      uri: "mongodb://user:pass@bigdata-iot-project_mongodb_1:27017/"
    database: "test"
    collection: "mosquito_logs"
    document: 
      message: "{{ read(trigger.uri) }}"

tasks:
  - id: logFromFile
    type: io.kestra.core.tasks.log.Log
    message: "{{ read(trigger.uri) }}" 
